# CVE Jira Processing Configuration

# Label applied to processed CVE issues
cve_processed_label: "os-as-infra-cve-triaged"

# Mapping of downstream repository names to upstream component names
# Used to group CVEs by component
repo_to_component:
  # cloud-provider-openstack
  openshift4/ose-openstack-cloud-controller-manager-rhel9: openshift/cloud-provider-openstack
  openshift4/ose-openstack-cinder-csi-driver-rhel9: openshift/cloud-provider-openstack
  openshift4/ose-openstack-cinder-csi-driver-rhel8: openshift/cloud-provider-openstack
  openshift4/ose-csi-driver-manila-rhel8: openshift/cloud-provider-openstack
  openshift4/ose-csi-driver-manila-rhel9: openshift/cloud-provider-openstack

  # csi-driver-manila-operator
  openshift4/ose-csi-driver-manila-rhel9-operator: openshift/csi-driver-manila-operator
  openshift4/ose-csi-driver-manila-rhel8-operator: openshift/csi-driver-manila-operator

  # openstack-cinder-csi-driver-operator
  openshift4/ose-openstack-cinder-csi-driver-rhel9-operator: openshift/openstack-cinder-csi-driver-operator
  openshift4/ose-openstack-cinder-csi-driver-rhel8-operator: openshift/openstack-cinder-csi-driver-operator
